# A Python API for `tennisabstract.com`
**Make sure to stick around until the end...**

In [ ]:
from construct_query import DownloadStats, ConstructURL
from datetime import datetime

### Download match data using a URL from a player's match data page.

In [ ]:
# copy/paste a URL from a stats page and load the info here
# (the printouts are just for debugging)
stat_url = 'http://www.tennisabstract.com/cgi-bin/wplayer-classic.cgi?p=BiancaAndreescu&f=Acx2019010120191201qqC2E0'
copied_stats = DownloadStats(url=stat_url)

wait_for_test 0

In [ ]:
print(f"{copied_stats.name} {copied_stats.title}")
copied_stats.match_data

Bianca Andreescu Matches (4-0) > Time Span: 01-Jan-2019 to 01-Dec-2019 [custom]; Level: All Tours; Round: Final

,Date,Tournament,Surface,Rd,Rk,vRk,Result,Won,Score,DR,...,Brkn,BPFaced,Time,TPW%,RPW%,vA%,v1st%,v2nd%,Brks,BPForced
0,26‑Aug‑2019,US Open,Hard,F,15,8,(15)Andreescu d. (8)Serena Williams [USA],1,6-3 7-5 (ch),1.15,...,3,8,1:40,53.1,50.6,11.7,26.5,69.8,6,13
1,5‑Aug‑2019,Toronto,Hard,F,27,10,Andreescu d. (8)Serena Williams [USA],1,3-1 RET (ch),1.50,...,<NA>,<NA>,0:19,56.7,50.0,11.1,14.3,72.7,1,3
2,4‑Mar‑2019,Indian Wells,Hard,F,60,8,(WC)Andreescu d. (8)Angelique Kerber [GER],1,6-4 3-6 6-4 (ch),1.09,...,3,4,2:18,51.5,41.8,0.0,33.8,57.6,4,10
3,21‑Jan‑2019,Newport Beach,Hard,F,106,113,(6)Andreescu d. (7)Jessica Pegula [USA],1,0-6 6-4 6-2 (ch),0.97,...,5,8,1:37,49.7,44.8,0.0,46.2,42.9,5,7

### Find the URL associated with a player's name.

In [ ]:
name = 'jo-WilfRIEd tsonGa' # capitalization doesn't matter
name_obj = ConstructURL(name, tour='ATP')
name_obj.URL

wait_for_test 0
wait_for_test 1
wait_for_test 2
wait_for_test 3
wait_for_test 0
wait_for_test 1
wait_for_test 2
wait_for_test 3
wait_for_test 0

'http://www.tennisabstract.com/cgi-bin/player-classic.cgi?p=JoWilfriedTsonga&f=ACareerqq'

## _Indepedently generate query URLs._

In [ ]:
gen_stats = DownloadStats('Serena Williams', 'WTA',
                          {'surface': ['carpet', 'clay'], 'level': 'premier',
                           'start date': datetime(1999, 8, 7),
                           'end date': datetime(2010, 4, 14),
                           'as rank': 'Top 5',
                           'round': ['R16', 'Round of 32']})

wait_for_test 0
wait_for_test 1
wait_for_test 2
wait_for_test 3
wait_for_test 0
wait_for_test 1
wait_for_test 2
wait_for_test 0

**in English**:
<br>
_Serena Williams matches in the Round of 32 or Round of 16 of Premier tournaments on clay or carpet between 7-8-1999 and 4-14-2010 where she was ranked in the top 5._

In [ ]:
print(f"{gen_stats.name} {gen_stats.title}")
gen_stats.match_data.head()

Serena Williams Matches (16-2) > Time Span: 07-Aug-1999 to 14-Apr-2010 [custom]; Surface: Clay, Carpet; Level: Premiers; Round: R16, R32; as Rank: Top 5

,Date,Tournament,Surface,Rd,Rk,vRk,Result,Won,Score,DR,...,Brkn,BPFaced,Time,TPW%,RPW%,vA%,v1st%,v2nd%,Brks,BPForced
0,4‑May‑2009,Rome,Clay,R32,2,20,Patty Schnyder [SUI] d. (2)Williams,0,6-2 2-6 6-1,0.87,...,5,6,<NA>,46.2,43.7,6.8,29.4,57.7,3,17
1,9‑Feb‑2009,Paris,Carpet,R16,1,145,(1)Williams d. (Q)Karolina Sprem [CRO],1,6-1 6-2,2.40,...,<NA>,<NA>,<NA>,62.9,51.9,3.8,47.6,54.8,5,11
2,9‑Feb‑2009,Paris,Carpet,R32,1,34,(1)Williams d. Iveta Benesova [CZE],1,6-1 6-4,<NA>,...,<NA>,<NA>,0:01,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
3,9‑May‑2005,Rome,Clay,R32,4,26,Francesca Schiavone [ITA] d. (3)Williams,0,7-6(2) 6-1,<NA>,...,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
4,4‑Apr‑2005,Amelia Island,Clay,R16,4,27,(2)Williams d. (14)Mary Pierce [FRA],1,7-6(5) 6-4,<NA>,...,<NA>,<NA>,0:04,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>

In [ ]:
# generate a more convoluted query, this time for an ATP player
gen_stats2 = DownloadStats('Andy Murr',
                           # don't need full name if there's only one match
                           'ATP',
                           {'vs height': 'Shorter', 'vs hand': 'right',
                            'vs entry': ['wild card', 'seeded'],
                            'as entry': 'seeded', 'vs current rank': 'inactive',
                            'vs rank': (14, 112),
                            'sets': ['straights', '4 of 5 sets'],
                            'score': 'all 7-6',
                            'exclude opp': ['Arnaud Clement', 'Guillermo Canas']})

wait_for_test 0
wait_for_test 1
wait_for_test 2
wait_for_test 0
wait_for_test 1
wait_for_test 2
wait_for_test 0
wait_for_test 1
wait_for_test 0
wait_for_test 1
wait_for_test 2
wait_for_test 0
wait_for_test 1
wait_for_test 2
wait_for_test 0
wait_for_test 1
wait_for_test 2
wait_for_test 0
wait_for_test 0

**in English**:
<br>
_Andy Murray matches where he was seeded -- and his opponent (who is not Arnaud Clement or Guillermo Canas) was right-handed, shorter than him, ranked between 14-112 at the time, was either seeded or given a wild card, and is currently inactive -- that ended in 4 sets or straight sets and featured at least 1 tiebreak._

In [ ]:
print(f"{gen_stats2.name} {gen_stats2.title}")
gen_stats2.match_data.head()

Andy Murray Matches (1-3) > Exclude: Arnaud Clement; Exclude: Guillermo Canas; Time Span: Career; Sets: Straights, 4-Setters; Scores: All tiebreaks; as Entry: Seeded; vs Rank: 14 to 112 [custom]; vs Curr Rank: Inactive; vs Entry: Seeded, Wild Card; vs Hand: Right; vs Height: Shorter

,Date,Tournament,Surface,Rd,Rk,vRk,Result,Won,Score,More,...,v2nd%,Brks,BPForced,TP,Aces,DFs,SP,1SP,2SP,vA
0,9‑Jun‑2014,Queen's Club,Grass,R16,5,42,(15)Radek Stepanek [CZE] d. (3)Murray,0,7-6(10) 6-2,<NA>,...,68.0,1,2,161,6,5,94,60,34,11
1,24‑Jun‑2013,Wimbledon,Grass,R16,2,26,(2)Murray d. (20)Mikhail Youzhny [RUS],1,6-4 7-6(5) 6-1,(wp),...,55.6,5,10,201,15,4,108,68,40,1
2,25‑May‑2008,Roland Garros,Clay,R32,12,20,(19)Nicolas Almagro [ESP] d. (10)Murray,0,6-3 6-7(3) 6-3 7-5,<NA>,...,38.2,2,5,262,10,9,136,67,69,21
3,30‑Oct‑2006,Paris Masters,Carpet,R16,19,27,(17)Dominik Hrbaty [SVK] d. (13)Murray,0,7-6(6) 6-0,<NA>,...,60.7,4,5,125,9,6,69,29,40,3

Confirm for youself that the title matches our earlier, plain English expectation.

*More extensive documentation on all available query filter is coming soon.*